services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
    env_file:
      - ./app/db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-drf-nginx-network
  drf:
    image: tyamadabiodataeng/django-drf
    container_name: drf
    build:
      context: ./app
      args:
        DIR_WORK: "/usr/src/app"
        ENV_YML: "environment.yaml"
        VENV: "bioinfo"
        REQ_DIR: "requirements/"
        REQ_TXT: "prod.txt"
    command: mamba run --name bioinfo gunicorn config.wsgi.prod:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    expose:
      - "8000"
    env_file:
      - ./app/db/.env
    depends_on:
      - postgres
    networks:
      - postgres-drf-nginx-network
  nginx:
    image: tyamadabiodataeng/django-drf-nginx
    container_name: nginx
    build: ./nginx
    volumes:
      - ./app/static:/usr/src/app/static
      - ./app/media:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - drf
    networks:
      - postgres-drf-nginx-network

networks:
  postgres-drf-nginx-network:
    driver: bridge

volumes:
  postgres_data:
